/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Todos API
 * The Todos API description
 * OpenAPI spec version: 0.1
 */

export interface CreateTodoDto {
  /** 追加するTodoのタイトル */
  title: string;
}
