/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Todos API
 * The Todos API description
 * OpenAPI spec version: 0.1
 */

export interface TodoDto {
  /** todoの完了状態 */
  completed: boolean;
  /** 作成日 */
  createdAt: string;
  /** todoのID */
  id: string;
  /** タイトル */
  title: string;
  /** 更新日 */
  updatedAt: string;
}
